//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtdelKadrov
{
    using System;
    using System.Collections.Generic;
    
    public partial class link
    {
        public int id { get; set; }
        public int id_сотрудника { get; set; }
        public int id_документа { get; set; }
    
        public virtual document document { get; set; }
        public virtual employee employee { get; set; }
    }
}
